name: continuous-integration/examples

on:
  push:
    branches:
      - main
    tags:
        - v*
    paths-ignore:
      - '**.gitignore'
      - '.images/**'
      - '**README.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.gitignore'
      - '.images/**'
      - '**README.md'


jobs:
  check:
    name: examples
    strategy:
      matrix:
        platform:
          # - ubuntu-latest
          - macos-latest
        toolchain:
          - stable
        job:
          - contract build
          - test

    runs-on: ${{ matrix.platform }}
    env:
      MULTI_CONTRACT_CALLER_SUBCONTRACTS: "accumulator adder subber"
      UPGRADEABLE_CONTRACTS: "delegator set-code-hash"
      RUST_BACKTRACE: full
    steps:

      - name: Checkout sources & submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          components: rust-src
          override: true

      - name: Rust Cache basic-contract-caller
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: basic-contract-caller


      - name: Rust Cache call-runtime
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: call-runtime

      - name: Rust Cache conditional-compilation
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: conditional-compilation

      - name: Rust Cache contract-terminate
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: contract-terminate

      - name: Rust Cache custom-allocator
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: custom-allocator

      - name: Rust Cache custom-environment
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: custom-environment

      - name: Rust Cache dns
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: dns

      - name: Rust Cache e2e-call-runtime
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: e2e-call-runtime

      - name: Rust Cache erc20
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: erc20

      - name: Rust Cache erc721
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: erc721

      - name: Rust Cache erc1155
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: erc1155

      - name: Rust Cache flipper
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: flipper

      - name: Rust Cache incrementer
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: incrementer

      - name: Rust Cache multi-contract-caller
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: multi-contract-caller

      - name: Rust Cache multisig
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: multisig

      - name: Rust Cache payment-channel
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: payment-channel

      - name: Rust Cache psp22-extension
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: psp22-extension

      - name: Rust Cache rand-extension
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: rand-extension

      - name: Rust Cache trait-dyn-cross-contract-calls
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: trait-dyn-cross-contract-calls

      - name: Rust Cache trait-erc20
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: trait-erc20

      - name: Rust Cache trait-flipper
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: trait-flipper

      - name: Rust Cache trait-incrementer
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: trait-incrementer

      - name: Rust Cache upgradeable-contracts/delegator
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: upgradeable-contracts/delegator

      - name: Rust Cache upgradeable-contracts/set-code-hash
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: upgradeable-contracts/set-code-hash

      - name: Rust Cache vesting
        uses: Swatinem/rust-cache@v2.7.0
        with:
          cache-on-failure: true
          workspaces: vesting


      # - name: Install `cargo-contract` `main`
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: --git https://github.com/paritytech/cargo-contract.git

      - name: Install `cargo-contract` `main`
        uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941 # v2.2.0
        with:
          crate: cargo-contract
          git: https://github.com/paritytech/cargo-contract.git

      - name: Install cargo-dylint
        uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941 # v2.2.0
        with:
          crate: cargo-dylint
          version: 1

      - name: Install dylint-link
        uses: baptiste0928/cargo-install@21a18ba3bf4a184d1804e8b759930d3471b1c941 # v2.2.0
        with:
          crate: dylint-link
          version: 1

      - name: Download and run latest `substrate-contracts-node` binary
        if: runner.os == 'Linux'
        run: |
          curl -L -o substrate-contracts-node.zip 'https://gitlab.parity.io/parity/mirrors/substrate-contracts-node/-/jobs/artifacts/main/download?job=build-linux' && \
          unzip substrate-contracts-node.zip && \
          chmod +x artifacts/substrate-contracts-node-linux/substrate-contracts-node &&
          ./artifacts/substrate-contracts-node-linux/substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

      - name: Download and run latest `substrate-contracts-node` binary
        if: runner.os == 'macOS'
        run: |
            curl -L -o substrate-contracts-node.zip 'https://gitlab.parity.io/parity/mirrors/substrate-contracts-node/-/jobs/artifacts/main/download?job=build-mac' && \
            unzip substrate-contracts-node.zip && \
            chmod +x artifacts/substrate-contracts-node-mac/substrate-contracts-node &&
            ./artifacts/substrate-contracts-node-mac/substrate-contracts-node -linfo,runtime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

      - name: Install and run latest `substrate-contracts-node` binary
        if: runner.os == 'Windows'
        run: |
            cargo install contracts-node --git https://github.com/paritytech/substrate-contracts-node.git --force --locked && \
            substrate-contracts-node -lruntime::contracts=debug  2>&1 | tee /tmp/contracts-node.log &

      - name: Output versions
        run: |
            cargo -vV
            cargo contract --version

      - name: ${{ matrix.job }} examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        if: runner.os == 'Windows'
        run: |
           $multi_contract_caller_subcontracts = "accumulator","adder","subber"
           foreach ($contract in $multi_contract_caller_subcontracts) {
               echo "Processing multi-contract-caller contract: $contract";
               cargo ${{ matrix.job }} --verbose --manifest-path multi-contract-caller/${contract}/Cargo.toml;
           }

           $upgradeable_contracts = "delegator","set-code-hash"
           foreach ($contract in $upgradeable_contracts) {
               echo "Processing upgradeable contract: $contract";
               cargo ${{ matrix.job }} --verbose --manifest-path upgradeable-contracts/${contract}/Cargo.toml;
           }

           foreach ($example in Get-ChildItem  -Directory "\*") {
               if ($example -Match 'artifacts') { continue }
               echo "Processing example: $example";
               cargo ${{ matrix.job }} --verbose --manifest-path=$example/Cargo.toml;
               cargo clean --manifest-path=$example/Cargo.toml;
           }

      - name: ${{ matrix.job }} examples on ${{ matrix.platform }}-${{ matrix.toolchain }}
        if: runner.os != 'Windows'
        run: |
           for contract in ${MULTI_CONTRACT_CALLER_SUBCONTRACTS}; do
               echo "Processing multi-contract-caller contract: $contract";
               cargo ${{ matrix.job }} --verbose --manifest-path multi-contract-caller/${contract}/Cargo.toml;
           done

           for contract in ${UPGRADEABLE_CONTRACTS}; do
                echo "Processing upgradeable contract: $contract";
                cargo ${{ matrix.job }} --verbose --manifest-path=upgradeable-contracts/$contract/Cargo.toml;
           done

           for example in ./*/; do
                if [ "$example" = "./artifacts/" ] || [ "$example" = "./upgradeable-contracts/" ]; then continue; fi;
                echo "Processing example: $example";
                cargo ${{ matrix.job }} --verbose --manifest-path=$example/Cargo.toml;
           done
